/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsButton {
        "block": boolean;
        "disabled": boolean;
    }
    interface DsInput {
        "idElement": string;
        "label": string;
        "type": 'email' | 'text' | 'password';
    }
    interface DsSwitch {
        "checked": boolean;
    }
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLDsInputElement extends Components.DsInput, HTMLStencilElement {
    }
    var HTMLDsInputElement: {
        prototype: HTMLDsInputElement;
        new (): HTMLDsInputElement;
    };
    interface HTMLDsSwitchElement extends Components.DsSwitch, HTMLStencilElement {
    }
    var HTMLDsSwitchElement: {
        prototype: HTMLDsSwitchElement;
        new (): HTMLDsSwitchElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "ds-input": HTMLDsInputElement;
        "ds-switch": HTMLDsSwitchElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        "block"?: boolean;
        "disabled"?: boolean;
    }
    interface DsInput {
        "idElement"?: string;
        "label"?: string;
        "type"?: 'email' | 'text' | 'password';
    }
    interface DsSwitch {
        "checked"?: boolean;
        "onApolloChange"?: (event: CustomEvent<boolean>) => void;
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
        "ds-input": DsInput;
        "ds-switch": DsSwitch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "ds-input": LocalJSX.DsInput & JSXBase.HTMLAttributes<HTMLDsInputElement>;
            "ds-switch": LocalJSX.DsSwitch & JSXBase.HTMLAttributes<HTMLDsSwitchElement>;
        }
    }
}
